// TODO this should start off empty?
export default [
  {
    _id: "1",
    title: "Q1 - HTML",
    availability: "Closed",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 29,
    "number-of-questions": 11,
    course: "RS101",
  },
  {
    _id: "2",
    title: "Q2 - CSS",
    availability: "Not Available until",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 32,
    "number-of-questions": 7,
    course: "RS101",
  },
  {
    _id: "3",
    title: "EXAM 1 FA 23",
    availability: "Closed",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 113,
    "number-of-questions": 20,
    course: "RS101",
  },
  {
    _id: "4",
    title: "Q3 - JS, ES6",
    availability: "Available",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 38,
    "number-of-questions": 13,
    course: "RS102",
  },
  {
    _id: "5",
    title: "Q3",
    availability: "Closed",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 31,
    "number-of-questions": 8,
    course: "RS102",
  },
  {
    _id: "6",
    title: "Q4 - NODE",
    availability: "Not Available until",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 25,
    "number-of-questions": 4,
    course: "RS102",
  },
  {
    _id: "7",
    title: "Q5 - MONGO",
    availability: "Available",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 38,
    "number-of-questions": 10,
    course: "RS103",
  },
  {
    _id: "8",
    title: "EXAM 2 FA23",
    availability: "Closed",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 104,
    "number-of-questions": 18,
    course: "RS103",
  },
  {
    _id: "9",
    title: "Q7",
    availability: "Closed",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 25,
    "number-of-questions": 4,
    course: "RS103",
  },
  {
    _id: "10",
    title: "Q8",
    availability: "Available",
    published: false,
    "due-date": "March 22 at 11:59 PM",
    points: 25,
    "number-of-questions": 4,
    course: "RS103",
  },
];
